package(default_visibility = ["//visibility:public"])

cc_library(
  name = "status",
  hdrs = ["status.h"],
  srcs = ["status.cc"],
)

cc_test(
  name = "status_test",
  srcs = ["status_test.cc"],
  deps = [":status"],
  timeout = "short",
) 
